### ISSUE TITLE
Problem Accessing Menu

### ISSUE THREAD

**Issue by SRock1944** [ogarcia/opensudoku#1]
I have a Samsung Galaxy G6, Android Version 5.1.1, last system update applied 12/11/2015 (G920VVRU4BOK7).

Original problem: Since the update, I have not been able to access the menu, so I cannot perform any of the operations (Undo, Restart, etc). 

Actions I took: 1. Force stopped Open Sudoku, turned off phone, turned phone back on ... still no access to the menu. 2. Uninstalled and reinstalled Open Sudoku ... lost all my previously downloaded puzzles and still have no access to the menu. 3. Copied Open Sudoku from old phone where it is working properly ... still no access to the menu. 4. Re-downloaded puzzles ... downloaded puzzles do not show up on the list of puzzles. I found that the downloaded puzzles were saved in the Downloads folder, not the Open Sudoku folder. I moved the files from downloads to the Open Sudoku folder, and the new puzzles still do not display on the list of puzzles.

Now there are 2 problems ... 1. no access to the menu and 2. downloaded puzzles don't get added to the list of available puzzles.

I considered just downloading a different Sudoku app, but yours is the one I like the best. I'd prefer to stay with yours.

**Comment by ogarcia** [comment]
Hello @SRock1944 

Sorry for delay in response, but I was on "holidays disconnection time". :smile:

The main problem is that some Sansung devices don't tell to applications that the task manage button not is a menu button, but there is a small trick to make it work:
1. Press and hold the dedicated task manage button. (situated in the area below your screen, to the left of your home button).
2. Keep it pressed for about 1 second and the menu will appear.

Please tell me if this fix your issue.

Greetings.

**Comment by SRock1944** [comment]
This workaround didn't work. When I press the task manage button, I get a message "This screen doesn't support split screen. ..."
Do you know why downloaded puzzles don't show up in the puzzle list? I verified that they are in the Open Sudoku folder. 
Shirley

Sent from my Verizon Wireless 4G LTE smartphone-------- Original message --------From: Óscar García Amor notifications@github.com Date: 1/4/2016  2:17 AM  (GMT-08:00) To: ogarcia/opensudoku opensudoku@noreply.github.com Cc: SRock1944 srock2@cox.net Subject: Re: [opensudoku] Problem Accessing Menu (#1) 
Hello @SRock1944 

Sorry for delay in response, but I was on "holidays disconnection time". 

The main problem is that some Sansung devices don't tell to applications that the task manage button not is a menu button, but there is a small trick to make it work:

Press and hold the dedicated task manage button. (situated in the area below your screen, to the left of your home button).
Keep it pressed for about 1 second and the menu will appear.

Please tell me if this fix your issue.

Greetings.

**Comment by ogarcia** [comment]
Hi,

I read in one forum that the main problem is the last update of the firmware. But one guy says:

Solution: Tap and hold the back button to get the menu options in s6 and s6 edge.

This works?

**Comment by SRock1944** [comment]
That doesn't work either (I have a Galaxy S6 and this has been a problem since the last firmware update).

**Comment by sworisbreathing** [comment]
I have the same issue on a Galaxy S6 running Android 6.0.1 (Marshmallow). Long-pressing the back button doesn't bring up the app menu (it just keeps backing me out of screens the longer I hold it down, taking me out of the app and back to the home screen). And if I try to long-press on the task manage button I get the "OpenSudoku does not support split screen view" message.

I've done a little bit of digging and it does look like there's some code changes required. I'm not an Android developer though so I'm not sure.

Per https://developer.android.com/guide/topics/ui/menus.html:
> Beginning with Android 3.0 (API level 11),... Android apps should... provide an app bar to present common user actions.

I've had a browse through the code and I'm not sure there is an app bar defined anywhere (again, not an Android developer, so apologies if I've overlooked it). If there isn't one, does the documentation for setting one up https://developer.android.com/training/appbar/index.html help at all?

**Comment by rewolff** [comment]
I'm on oreo now and ... Same problem. I am now in full screen mode with gestures for the task switcher And back buttons. So there is no "...and hold it down".

I have already tried going back, but it is difficult: I keep doing the gestures. I'll try the longpress now.

Update: long press on switch app works... ..
