### ISSUE TITLE
open-sudoku in Windows 10 ???

### ISSUE THREAD

**Issue by afgcons** [ogarcia/opensudoku#10]
First I read README, then (intuitively) double-clicked gradlew.bat - no go! So I sought guidance on the gradle website, downloaded and successfully installed the latest version, and, and, ... no go!

Where can I find Windows install instructions ?

**Comment by ogarcia** [comment]
This application is only for Android, not for Windows. If you have an Android Phone or Tablet you can install it from [here](https://play.google.com/store/apps/details?id=org.moire.opensudoku).
