### ISSUE TITLE
Can't open downloaded .opensudoku files

### ISSUE THREAD

**Issue by MrGibbage** [ogarcia/opensudoku#103]
Pixel 5, running Android 11. When I click on Import, and navigate to my Downloads, no files are listed, even though there are several .opensudoku files in there. I have granted media/file permissions when asked. Also, if I go the file browser and click on the file, three app choices appear, but none of them are Opensudoku. I don't know if it will help, but my only three choices are KeePassDroid, Stocard and OsmAnd+

**Comment by autinerd** [comment]
Yeah, it's because Android 11 changes a lot in terms of storage access: https://developer.android.com/about/versions/11/privacy/storage

The app needs to be adjusted to Android 11.

**Comment by MrGibbage** [comment]
Thanks for replying! Is updating the app to Android 11 something that can be done soon-ish? Or do you see it as a long range goal or something that can't easily be done at all? Hoping that it can be done! I have tried several Sodoku apps and yours is the best!
