### ISSUE TITLE
Unable to import puzzles

### ISSUE THREAD

**Issue by Irihapeti** [ogarcia/opensudoku#107]
I've been generating sudoku .sdm files using the terminal program _sudoku_ in Linux, which are then imported into Open Sudoku. Import has stopped working in the 3.6.0 version.

I get the following error:

`Unknown error occurred while importing puzzles; import was cancelled`

Open Sudoku doesn't crash.

.xml files from generating puzzles online import successfully.

Android version: 10 (3 different devices)
Opensudoku version 3.6.0 fron F-droid

**Comment by ogarcia** [comment]
@Irihapeti please, attach a sample file in the issue

**Comment by Irihapeti** [comment]
File attached. 

I've had to change the extension from .sdm to .txt, otherwise Github won't accept it.
[puzzles_hard.txt](https://github.com/ogarcia/opensudoku/files/5889794/puzzles_hard.txt)

**Comment by ogarcia** [comment]
Bug found :wink:

**Comment by Irihapeti** [comment]
Confirmed that import is now working. Many thanks!
