### ISSUE TITLE
[RFC] Remove changelog alerts from within the app

### ISSUE THREAD

**Issue by anthonyryan1** [ogarcia/opensudoku#108]
Someone I was having a passing discussion with recently made a comment to me about wanting a Sudoku game on their phone again.

I promptly suggested they install Open Sudoku, telling them it was free and great. She immediately went into the Google Play store and installed Open Sudoku. Within less than 30 seconds of installing it, she deleted it and promptly installed some other sudoku app off the app store that had ads all over the screen.

I asked what the problem with Open Sudoku was? She said the first thing she saw when she opened the game was a stupid pop-up, and if it was going to be showing pop up ads before she even started playing it was clearly garbage.

Confused I cleared the storage on my phone for OpenSudoku and re-opened it. There was a ChangeLog pop-up before anything else was shown.

As a non-technical person she just saw a changelog and immediately wrote off the application as "worse than average".

I wonder if it would be worth optimizing the first-play flow. Getting people into a game as quickly as possible, without alerts or configuration choices before they start playing.

Would welcome thoughts on whether or not this change would improve the usability for non-technical people.

**Comment by ogarcia** [comment]
Sorry, but changelog is a feature loved by users and a way to credit the code collaborators. The window only appear once and with a very very very descriptive title: __News__ (not changelog or log) and descriptions easy to understand. If your friend mistook it with an ad she just didn't read it. No technical knowledge required to read a text that says, _we updated the german translation_ or _add a menu option to undo before mistake_.
