### ISSUE TITLE
This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.1 or newer.

### ISSUE THREAD

**Issue by Salman5027** [ogarcia/opensudoku#109]
when i import this project in intelij idea it hive this error message : This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.1 or newer.   please help me to solve this problem

**Comment by ogarcia** [comment]
You must use [latest version](https://developer.android.com/studio#downloads) of [Android Studio](https://developer.android.com/studio).

**Comment by Salman5027** [comment]
After updating my Android studio to Newer version- the problem solved finally
