### ISSUE TITLE
Request: Allow undo-ing moves after done solving

### ISSUE THREAD

**Issue by leogott** [ogarcia/opensudoku#110]
**Status quo:** when all numbers were entered correctly, the sudoku is locked, and no moves can be undone.

**Request:** after the sudoku was finished, don't block undo and returning to a checkpoint.

**Reasoning:** Sometimes, when getting stuck on a sudoku, one might try around and see if entering a number leads to a valid solution or not. If the path leads to a solution, one might want to go back and try understanding how the solution could be found without trial&error, or check if there really is only one solution.

**Comment by chrisawad** [comment]
I like your suggestion. +1

I find myself stopping just shy of completing to avoid not being able to undo

**Comment by ogarcia** [comment]
I'm migrating Open Sudoku development from GitHub to GitLab. To make the migration as clean as possible I'm going to close this issue. If you are still interested (or if it is still relevant), please open it again in [GitLab](https://gitlab.com/opensudoku/opensudoku) from July 26.

Thank you very much for your understanding.
