### ISSUE TITLE
Request: Support for some non-standard variants of sudoku by coloring individual cells

### ISSUE THREAD

**Issue by leogott** [ogarcia/opensudoku#112]
I'd love to see support for some sudoku variants in open-sudoku, which would require additional constraints to be represented visually somehow.
A lot could be achieved by having the option to color individual cells' backgrounds when adding a new sudoku.

If this feature is desired in open sudoku, I'd gladly offer work on it, but require some guidance.

More thoughts on the matter:
Personally, aside from the default I'd choose black/contrast, two shades of gray, as well as the primary and secondary colors RGB CMY. Black is sometimes used to mark cells which either contain a number or not, but can't be edited either way.

I'm not sure how this would interact with highlighting.

This would obviously need more thoughts with regards to themes and accessibility. As the actual color is rarely important, just to distinguish them, optionally using patterns and color would work for both, and transforming/rotating the colors in the color space might work for themes.

**Comment by ogarcia** [comment]
This is completely outside the scope of the application. It would require almost a complete new implementation, so I see it as complicated to address in the future.
