### ISSUE TITLE
[Enhancement] Add an Ascending/Descending toggle to the Sort function

### ISSUE THREAD

**Issue by e-t-l** [ogarcia/opensudoku#114]
For the Sort option, can we add an Ascending/Descending toggle? (Personally, I would mainly want this so that completed puzzles appear at the _bottom_ of the list, not the top.)

**Comment by demield** [comment]
Hello, you can use filter option to hide already solved puzzles.

Anyway, I've modified sorting dialog, so player can choose sorting order by tapping on corresponding button ("ASC" or "DESC").
Now it looks like this.
![Screenshot from 2021-04-02 16-07-40](https://user-images.githubusercontent.com/22031408/113419260-bf2f6600-93cf-11eb-8ec9-e59c8fa2598f.png)

My friend gave me an idea to put sort and filter options onto a separate panel (something like a navigation drawer), so player can just swipe to reveal them.
@ogarcia What do you think?

**Comment by ogarcia** [comment]
> Anyway, I've modified sorting dialog, so player can choose sorting order by tapping on corresponding button ("ASC" or "DESC").

Great idea :wink: 

> My friend gave me an idea to put sort and filter options onto a separate panel (something like a navigation drawer), so player can just swipe to reveal them.
> @ogarcia What do you think?

In that case all menu options must be in the drawer, something like YouTube app when you press in your picture

**Comment by ogarcia** [comment]
Done in 3.8.0
