### ISSUE TITLE
UI improvement (with mockup)

### ISSUE THREAD

**Issue by Nikoichu** [ogarcia/opensudoku#115]
There are some things in the user interface that make no sense to me, especially in Landscape mode on devices with large (and/or long) screens. Here I've made a screenshot of the current UI and a mockup of an improved UI:
CURRENT:
![UI_current](https://user-images.githubusercontent.com/42444745/109787774-404fdd80-7c17-11eb-8b47-ad5e28185b4e.png)
IMPROVED:
![UI_proposal](https://user-images.githubusercontent.com/42444745/109787775-40e87400-7c17-11eb-838e-5b6111d36697.png)

1. Why are the numbers and text on the input buttons so small? They barely take up 10% of the space available for them. This could be a slider users can drag in the theme settings to determine how big the text is. Also, the number in brackets (9) that shows how many of a certain number is present should NOT be the same size or color and in the same place as the input number, that is really confusing.
2. In landscape mode, the grid is WAY too small, it takes like a third of my screen, and consequently, the input keys are WAY too big, to the point of 1, 4 and 7 being too far for my thumb to reach comfortably. That is because of the useless header stretching all the way across the screen when it doesn't need to (lichess is guilty of the same thing). The small grid combined with the out-of range buttons make playing in landscape a really uncomfortable experience.

**Comment by gsker** [comment]
This looks like an improvement. Could we see a mockup of the Portrait mode too?

**Comment by Nikoichu** [comment]
@gsker Well besides the number in brackets being smaller and in the corner, and the others being larger, the portrait mode one would be identical with what we have now, because it already IS using all the screen width that it can, whereas the landscape one gets shrinked by the header bar.

**Comment by pan64** [comment]
this looks for me at least three different issues:
1. header in landscape mode
2. move counters to the bottom right corner
3. increase the size of those numbers

**Comment by ogarcia** [comment]
I'm migrating Open Sudoku development from GitHub to GitLab. To make the migration as clean as possible I'm going to close this issue. If you are still interested (or if it is still relevant), please open it again in [GitLab](https://gitlab.com/opensudoku/opensudoku) from July 26.

Thank you very much for your understanding.
