### ISSUE TITLE
"8" note gets a bit hidden by Block grid

### ISSUE THREAD

**Issue by Porrumentzio** [ogarcia/opensudoku#116]
I suppose it also happens with 7 and 9
![Screenshot_20210314-213201](https://user-images.githubusercontent.com/61913683/111083284-16e35b80-850d-11eb-8720-28330dc1558e.png)

**Comment by ogarcia** [comment]
I'm migrating Open Sudoku development from GitHub to GitLab. To make the migration as clean as possible I'm going to close this issue. If you are still interested (or if it is still relevant), please open it again in [GitLab](https://gitlab.com/opensudoku/opensudoku) from July 26.

Thank you very much for your understanding.
