### ISSUE TITLE
"Undo" should highlight the action just being undone

### ISSUE THREAD

**Issue by favonia** [ogarcia/opensudoku#119]
Currently, "undo" will highlight the action _before_ the action being undone. However, I believe it looks better to highlight the action just being undone, or maybe both.

**Comment by ogarcia** [comment]
I'm migrating Open Sudoku development from GitHub to GitLab. To make the migration as clean as possible I'm going to close this issue. If you are still interested (or if it is still relevant), please open it again in [GitLab](https://gitlab.com/opensudoku/opensudoku) from July 26.

Thank you very much for your understanding.
