### ISSUE TITLE
Timer corruption at end of game.

### ISSUE THREAD

**Issue by bgordo3** [ogarcia/opensudoku#131]
After completing puzzle time is displayed. If you then undo/redo the last move, the correct completion time is displayed, but an exceedingly large completion time is posted to the summary table.

![Screenshot_20210916-212217](https://user-images.githubusercontent.com/16109061/133717121-405ad3c6-c07b-47b5-b02e-fac8811b8918.png)

![Screenshot_20210916-212228](https://user-images.githubusercontent.com/16109061/133717166-a5f5eaa6-8076-479d-9f8e-cf47afa4662f.png)

![Screenshot_20210916-212241](https://user-images.githubusercontent.com/16109061/133717187-f80437e7-032c-4442-9c94-ccf9b71bde2d.png)

**Comment by ogarcia** [comment]
I'm migrating Open Sudoku development from GitHub to GitLab. To make the migration as clean as possible I'm going to close this issue. If you are still interested (or if it is still relevant), please open it again in [GitLab](https://gitlab.com/opensudoku/opensudoku) from July 26.

Thank you very much for your understanding.
