### ISSUE TITLE
Enhancements to opensudoku.moire.org

### ISSUE THREAD

**Issue by mef** [ogarcia/opensudoku#134]
Hi,

I am occasionally using the puzzle generation feature hosted at opensudoku.moire.org, browsing from a mobile device.

One issue that I meet is that no visual feedback is displayed whenever I tap on a puzzle generation link, so I am never sure about whether the puzzle generation is started or not.

I would like to propose the following enhancements:

* Run the puzzle generation inside a web worker, so that the page does not freeze while the puzzles are being generated. This works on all recent browsers except Opera Mini ([source](https://caniuse.com/webworkers)).
* Display a progress bar or spinner during the puzzle generation.

Would you be interested in a pull request addressing these?

**Comment by ogarcia** [comment]
> Would you be interested in a pull request addressing these?

Yes, thanks!
