### ISSUE TITLE
Coloured cells?

### ISSUE THREAD

**Issue by HammyHavoc** [ogarcia/opensudoku#137]
Hi!

I'm new to sudokus relatively speaking.

What do the different colors of cell represent on the default OpenSudoku theme? E.g. the light baby blue cells are obviously pre-filled cells. But what about the black cells and white cells?

Apologies if this is a ridiculously obvious question, the 2am brain may be in full effect.

Great work though, looking forward to hopefully being able to contribute in some form. It certainly beats using a sudoku website in a browser!

**Comment by ogarcia** [comment]
They have no special function beyond giving a clear view of the game board. :wink:
