### ISSUE TITLE
Burn in Mode

### ISSUE THREAD

**Issue by calhix** [ogarcia/opensudoku#138]
First I gotta say props to the devs and contributors, this app is really great and I can't really think of anything I'd have different. I've gotten more addicted to Sudoku lately and have noticed some burn in (LCD screen on a Moto G7) after having it on the same screen for a while. I've fixed it by downloading a dead pixel fixer app and it actually has done the trick so far (twice). I would like to suggest a burn in mode where the theme of the app changes between dark and light mode and the user is able to set how often the theme changes, maybe 5 min, 10 min, 30 min, etc since the burn took under 10 min of being on the same screen. Also it would be best to be able to set a schedule of when it takes effect since at night I don't think there is an issue since I'm playing with very low brightness and don't want to be blinded.

**Comment by ogarcia** [comment]
Welcome to the screen problem that certain Motorola models have. Mine has it too. There is nothing you can do, even if you change the colors every so often the screen is still marked. It is a manufacturing defect of certain models of the G range and there is nothing that can be done. :disappointed:
