### ISSUE TITLE
Phantom key presses

### ISSUE THREAD

**Issue by Mpk320** [ogarcia/opensudoku#141]
I get lots of phantom key presses when I play, anything from adding and deleting numbers to beginning to pull down the status bar. This is the only app that does this on my phone (pixel 4xl)

**Comment by ogarcia** [comment]
I'm migrating Open Sudoku development from GitHub to GitLab. To make the migration as clean as possible I'm going to close this issue. If you are still interested (or if it is still relevant), please open it again in [GitLab](https://gitlab.com/opensudoku/opensudoku) from July 26.

Thank you very much for your understanding.
