### ISSUE TITLE
Creation of matrices in different sizes

### ISSUE THREAD

**Issue by kubilay-eren** [ogarcia/opensudoku#15]
Hi, I want to make some changes in the project. I want to create sudoku puzzles in different sizes. As an example I would like to have "4x4 or 3x3" puzzles. But there are only "9x9" puzzles in it. Do you have any idea how I can make this improvement?

**Comment by prasadrathod** [comment]
Hey...
Sudoku is mostly design for the size of perfect square numbers like 4x4, 9x9..16x16 and so on....

I can help you to do so upto 16x16 but ....
I don't know much about Android UI....
I will work it out and will then sent pull request.. Thanks!

**Comment by kubilay-eren** [comment]
Thank you.

**Comment by ogarcia** [comment]
@JagsPvr any PR is always welcomed

**Comment by ogarcia** [comment]
For now the objective of this app is to be the best option for classic Sudoku, all PR are always welcomed, but for now this feature are at bottom of list
