### ISSUE TITLE
Inclusion in F-Droid

### ISSUE THREAD

**Issue by Poussinou** [ogarcia/opensudoku#19]
Hi,

Since this app is GNU GPLv3 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind, that do not use Google Play nor anything else, except F-Droid.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by ogarcia** [comment]
Hi @Poussinou 

Feel free to add app to F-Droid, but I don't support it officially. Sorry, but I have a very bad experience with Ultrasonic updates in F-Droid.

Greetings.

**Comment by Poussinou** [comment]
OK I'll have a look at this (Request For Packaging [here](https://gitlab.com/fdroid/rfp/issues/591))

What was wrong with Ultrasonic updates in F-Droid? How could we help you?

**Comment by ogarcia** [comment]
Don't worry. We have an issue opened for Ultrasonic here: https://gitlab.com/fdroid/fdroiddata/issues/1107
