### ISSUE TITLE
Sort the resolved puzzles

### ISSUE THREAD

**Issue by guy-teube** [ogarcia/opensudoku#24]
Hi there, 
I have downloaded the packs with 100 puzzles in Easy/Medium/Hard difficulty. But I when I have resolved a lot of these puzzles, I have to scroll a lot to find the first one unresolved. I would like to sort the list, to have the unresolved ones at the top of the list, and the resolved ones below. Or maybe to hide completely the resolved ones. 
Thank you

**Comment by rewolff** [comment]
How about a small button: "hide solved"? 
(I have the same problem, just bigger: I found a "learning curve" sudoku set. Much more difficult than "Hard"... And 2500 puzzles....).

**Comment by ogarcia** [comment]
In the list, if you enter into menu, you have a _filter_ option where you can choice what to show. And there is a new feature in #56 a new title screen with a button to _Resume_ last played puzzle.
