### ISSUE TITLE
Remove fill in notes when a matching number is entered

### ISSUE THREAD

**Issue by rogerm4242** [ogarcia/opensudoku#31]
I like to solve sudoku by using "Fill in notes". I would love a feature that removed notes that are no longer valid because of a number I enter in a row, column, or box.

**Comment by SeriousM** [comment]
I support this feature request, this would be very useful!

**Comment by jlnordin** [comment]
I agree! PR #61 submitted for this feature.

**Comment by rogerm4242** [comment]
@jlnordin, Thank you for your work on this open source application. 

The "highlight notes that match a number" feature is also very cool!
