### ISSUE TITLE
Timer resets under certain conditions with PIP mode

### ISSUE THREAD

**Issue by hellow554** [ogarcia/opensudoku#33]
I do watch Netflix via the picture  in picture feature from android. I switch from time to time to start the next episode. I notice sometimes when I get back to my open Sudoku that the timer resets to 0:00. I'm not sure if that has anything to so with the PIP feature. 

I'm using android 8.1.0 with lineage OS 15.1

**Comment by hellow554** [comment]
![Screenshot_OpenSudoku_20190402-180404](https://user-images.githubusercontent.com/921462/55417891-d97ca200-5571-11e9-82fc-c12992c3a9e4.png)
![Screenshot_System-UI_20190402-180407](https://user-images.githubusercontent.com/921462/55417900-de415600-5571-11e9-972a-7a622d488dd4.png)
![Screenshot_OpenSudoku_20190402-180410](https://user-images.githubusercontent.com/921462/55417907-e1d4dd00-5571-11e9-89ef-256bfe1de2fa.png)

This is the setup:
I have Netflix running in PIP mode, whenever I click on the pip image it will get slightly bigger and the timer immediately stops and when I let the PIP get small again the timer will start at 0.
This is reproducable 👍

**Comment by ogarcia** [comment]
I'm migrating Open Sudoku development from GitHub to GitLab. To make the migration as clean as possible I'm going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/opensudoku/opensudoku) from July 26.

Thank you very much for your understanding.
