### ISSUE TITLE
an exception when testing app

### ISSUE THREAD

**Issue by WangGuox1n** [ogarcia/opensudoku#34]
Hi, I developed an automatic-testing tool and it detected an exception in your app(version 2.5.2).
I would like to know if you consider it as a bug?

**STACK_TRACE**=E/AndroidRuntime(15168): FATAL EXCEPTION: main
E/AndroidRuntime(15168): Process: org.moire.opensudoku, PID: 15168
E/AndroidRuntime(15168): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.moire.opensudoku/org.moire.opensudoku.gui.FileListActivity}: java.lang.NullPointerException
E/AndroidRuntime(15168): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
E/AndroidRuntime(15168): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
E/AndroidRuntime(15168): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/AndroidRuntime(15168): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/AndroidRuntime(15168): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(15168): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(15168): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime(15168): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(15168): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(15168): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(15168): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime(15168): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(15168): Caused by: java.lang.NullPointerException
E/AndroidRuntime(15168): 	at java.io.File.fixSlashes(File.java:185)
E/AndroidRuntime(15168): 	at java.io.File.<init>(File.java:134)
E/AndroidRuntime(15168): 	at org.moire.opensudoku.gui.FileListActivity.onCreate(FileListActivity.java:81)
E/AndroidRuntime(15168): 	at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime(15168): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime(15168): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
E/AndroidRuntime(15168): 	... 11 more

**Comment by ogarcia** [comment]
Must fixed in 2.6.0
