### ISSUE TITLE
Android theme selector/editor

### ISSUE THREAD

**Issue by ogarcia** [ogarcia/opensudoku#41]
Current theme selector only changes the board theme. There is some users that want change interface (buttons, menu, texts...) colours. Maybe making changes to Theme.AppCompat.

**Comment by jlnordin** [comment]
Oscar, I'm currently working on this issue as a follow-on to the theme preview change that was just merged in. As part of this I'm planning on adding some more built-in themes with some different color options, including an AMOLED theme per issue 23 as well as an "Open Sudoku" Theme that is based off of the green-and-grey color scheme used in the app's icon.
