### ISSUE TITLE
Add stupid fill in notes

### ISSUE THREAD

**Issue by DamienCassou** [ogarcia/opensudoku#44]
Would it be possible to have a "fill in notes" action that fills each empty cell with every number from 1 to 9? The current "fill in notes" behavior does some more work that I would prefer doing myself to avoid making the game too simple.

**Comment by rewolff** [comment]
Find the "learning curve" sudoku set. That should still provide a challenge even with the current fill-in-notes.

**Comment by telematoxx** [comment]
Exactly this function is what i want. It's useful for a solving strategy, where the valid value range is to be steadily restricted (with help of notes) until - hopefully - the unambiguous solution is left.
