### ISSUE TITLE
Request: highlight permanent numbers

### ISSUE THREAD

**Issue by WyntrHeart** [ogarcia/opensudoku#47]
Being unable to see which numbers I can't move makes problem solving almost impossible and forces me to start over completely when I get stuck

**Comment by rewolff** [comment]
What i do is save checkpoint before i put in a number i am not sure of.

**Comment by jlnordin** [comment]
@WyntrHeart 

All the current themes change the background color of permanent numbers vs. numbers you have entered. The contrast on those colors is intentionally low, but if you wanted to make it clearer, you could customize it with the a custom theme. Easiest way would be:

1. Go to settings -> theme -> select "custom theme".
2. Go to settings -> custom theme colors -> select "generate from existing theme..." and pick a theme as your starting point (such as the Open Sudoku theme).
3. Select "Background of read-only cells" to change the color behind the permanent numbers.

Let me know if that isn't quite what you were thinking.
