### ISSUE TITLE
Generate random sudoku

### ISSUE THREAD

**Issue by wuniversales** [ogarcia/opensudoku#54]
It would be nice to be able to generate a random sudoku.

To do this you simply have to use random numbers and check that in the same row, or line, they are not repeated.
This would generate the solution of a sudoku.
Then you simply have to hide numbers according to the level of difficulty.

- For example, at the easy level, just delete three numbers from each number.
- In the middle level hide four numbers of each number, also omit some number, for example the two, so that no two appear.
- At the extreme level, hide three numbers from each number, and not two numbers appear.

More or less that is the idea, obviously the levels of difficulty are indicative, perhaps he has to show more numbers, or less.

Greetings and good application

**Comment by rogerm4242** [comment]
FWIW, I was able to generate random sudoku with Hodoku.

http://hodoku.sourceforge.net/en/index.php

I made a simple, hackish python script to convert the puzzles so they can be imported into OpenSudoku.

https://bitbucket.org/rogerm4242/hodoku-to-opensudoku/src/master/

I really like Hodoku's puzzle generator / solver. It allows you to make puzzles that are guaranteed to be solvable. You can also choose the difficulty level and techniques needed to solve the puzzles. 

This could be made much more elegant, but I only use it once every couple of years. It allows me to generate a list of a thousand or so random puzzles and does what I want.

Edit: Hodoku is an open source java application. Maybe it's generator code functions could be imported into OpenSudoku?? (I am not a developer, so maybe not)

**Comment by ogarcia** [comment]
In [Open Sudoku web](https://opensudoku.moire.org/) you can generate puzzles without problem.

**Comment by rogerm4242** [comment]
Thanks ogarcia, Somehow I missed that option before.

Open Sudoku is a great app. I really like the new option to highlight cells with similar values!
