### ISSUE TITLE
When selecting a digit with no filled cells, notes containing that digit are not highlighted.

### ISSUE THREAD

**Issue by Biotronic** [ogarcia/opensudoku#69]
If one digit is not present on the board, but is used in notes, selecting that digit in SN mode does not highlight the cells with those notes. 

To replicate the issue:
1) Start a game where one or more digits are not present.
2) Choose SN mode and note mode, then select a digit that's not present on the board.
4) Place a note in an empty cell.
5) Choose a digit that's already in a filled cell.
6) Choose the digit of the note again.
7) Notice that the digit chosen in step 5) is still highlighted, and the notes with the digit you chose in step 6) are not.

**Comment by rogerm4242** [comment]
Here is a sample layout showing this bug.

![Screenshot_20200315-134835](https://user-images.githubusercontent.com/13337800/76810324-0f875600-67c4-11ea-92c5-bc6f42463e7c.png)

**Comment by victoredier** [comment]
![Screenshot_20200515-003017](https://user-images.githubusercontent.com/808014/82014981-57e7b680-9643-11ea-8a0a-0d23c11c4105.png)
Hi
I can replicate this issue, in this screenshot my previous selection was '3' and now my selection is '4'
Note how there are not any more 4 in the board.
