### ISSUE TITLE
Feature request: reset all games in a folder or during import

### ISSUE THREAD

**Issue by gsker** [ogarcia/opensudoku#72]
I recently imported some old games to play them and realized I was either going to have to reset them as I played them or go through and reset 300 games one after another. And I was not going to be able to put them in a not played state.  My options were to edit the xml to get rid of the state data or change the application.    

I edited OpenSudokuImportTask.java to set state, time, and lastPlayed to default values and recompiled.    

It worked fine but I'd like to have that as an option either to reset a folder, or to not include the played data during an import.  I'm not a programmer -- I'm only able to do very simple things and would hose up the code if I tried.

**Comment by ogarcia** [comment]
Fixed. Added an option to reset all puzzles in a folder. It will be included in next version.
