### ISSUE TITLE
Make creating own sudokus more obvious

### ISSUE THREAD

**Issue by cweiske** [ogarcia/opensudoku#75]
I was stuck solving a sudoku in my local newspaper and wanted to "import" it manually to get a hint what do do next.

It took some time until I found out that I had to create a sudoku list before I could add one. 

There should be a button on the "sudoku lists" page to create an own sudoku.

**Comment by ogarcia** [comment]
But add a Sudoku by hand cannot be more simple. You go to any sudoku list and press three points menu -> Add sudoku

**Comment by leogott** [comment]
Adding new sudoku is indeed very simple! However: it's not entirely intuitive that new users have to be inside a folder to access the "Add Sudoku" option. It wasn't the first place I looked. (Also in the title screen folders are called lists, for some reason?)

So easy ways to address this would be to:
- include the information in the First Launch Hints
and/or
- add a "add sudoku" button in the folders view, which, when pressed, prompts you to select a folder in which to add the new sudoku
or
- add a text element in the folders view, which says something like "Hint: You can add new sudoku from within a folder"

**Comment by ogarcia** [comment]
I'm migrating Open Sudoku development from GitHub to GitLab. To make the migration as clean as possible I'm going to close this issue. If you are still interested (or if it is still relevant), please open it again in [GitLab](https://gitlab.com/opensudoku/opensudoku) from July 26.

Thank you very much for your understanding.
