### ISSUE TITLE
Hint: Show fields that can be solved next

### ISSUE THREAD

**Issue by cweiske** [ogarcia/opensudoku#76]
I got stuck solving a sudoku in my local newspaper and wanted to use OpenSudoku to get a hint what to do next.

Unfortunately, the hint functionality shows the number of any selected cell.

It would be nice if OpenSudoku would have a hint functionality that highlights the fields that can be solved next - just what one can deduce from the currently available numbers.

**Comment by jlnordin** [comment]
I'm actually working on such a feature right now! It's pretty complex, but
I'll hopefully have something to share soon. :-)

**Comment by ogarcia** [comment]
@cweiske in meantime you can enable and use the "Fill in notes" option, maybe helps you to solve puzzle without use the hint option

**Comment by ogarcia** [comment]
I'm migrating Open Sudoku development from GitHub to GitLab. To make the migration as clean as possible I'm going to close this issue. If you are still interested (or if it is still relevant), please open it again in [GitLab](https://gitlab.com/opensudoku/opensudoku) from July 26.

Thank you very much for your understanding.
