### ISSUE TITLE
Note screen colors

### ISSUE THREAD

**Issue by cskaryd** [ogarcia/opensudoku#8]
Could you change (or add an option to change) the color of the selected notes?  To my color blind eyes it is very hard to distinguish between selected numbers and deselected numbers.

**Comment by spimanov** [comment]
Hi!
I have just unintentionally found this message. 
Not sure that it's still actual, but I guess it's possible to add the such kind of functionality. Will do it

**Comment by cskaryd** [comment]
I tried to make this change myself, but haven't had any experience with
Android development.  The white and cyan are just so close for my eyes that
it's incredibly hard to determine which numbers are selected on the note
screen.

Thanks for taking a look!  I look forward to the diff to see how you do it.

**Comment by spimanov** [comment]
Hello guys!
Let's check it. I've sent a pull-request: [Custom theme settings](https://github.com/ogarcia/opensudoku/pull/13)
@ogarcia I would suggest to modify existing themes - they are almost similar.

**Comment by ogarcia** [comment]
Thanks @spimanov is a great change!

I will merge it now and make small changes into themes, If you have ideas for new themes they are welcomed.

**Comment by ogarcia** [comment]
Published new version 2.5.0 in Play Store with changes. I make small modifications in existing themes, but they are thinked only to show what do you change. Basically the themes are the same but with inverted colors.

@spimanov a posible enhancement could be add a text color setting for secondary, touched, selected and highlighted cell (or only for selected and highlighted).

@opalCSkaryd I add a high contrast theme to color blind people. What do you think about it?

**Comment by cskaryd** [comment]
Hi @ogarcia -

Unless I'm missing an option, I don't see the change.  Or perhaps I needed to be more specific regarding the issue.  The lines at the bottom of the buttons for #s 5 and 6 [as shown here](http://tux.theopalgroup.com/~cskaryd/sudoku.png) is what I was referring to.  5 is unselected, where 6 is selected.  Is there a way to set the color scheme for that 1 pixel line at the bottom of the Edit Note number button?

Thanks!

**Comment by ogarcia** [comment]
@opalCSkaryd the main problem about this is that the button desing is a part of Android system.

To change interface colors that the app must be rewrited and (I think) this broke the old android version support.

I suggest you to use other input method as _NUM PAD_ and see the anotations directly in board.

**Comment by ogarcia** [comment]
The original issue is fixed now. I created #41 to follow app theme enhancement
