### ISSUE TITLE
[Bug] Display problem

### ISSUE THREAD

**Issue by wuniversales** [ogarcia/opensudoku#83]
It seems that the application does not refresh the lower buttons when clicking on any box in the sudoku, I have to click on the dropdown menu so that the lower numbers appear again.

![IMG_20200530_011412_545](https://user-images.githubusercontent.com/48658161/83312539-eac34c00-a212-11ea-8524-0fbaa69d3f5b.jpg)

Android version: 4.4.2
Opensudoku version: 3.4.0 (f-droid)

**Comment by ogarcia** [comment]
I'm migrating Open Sudoku development from GitHub to GitLab. To make the migration as clean as possible I'm going to close this issue. If you are still interested (or if it is still relevant), please open it again in [GitLab](https://gitlab.com/opensudoku/opensudoku) from July 26.

Thank you very much for your understanding.
