### ISSUE TITLE
Add second note mode to show that only specific digits can go into a cell

### ISSUE THREAD

**Issue by saviola777** [ogarcia/opensudoku#84]
Hello,

thanks for another great piece of open source software. I have a small feature request: when entering notes, I sometimes just jot down single digits to note that they have to go there in this row/column/box, but other digits can also go into these cells. Other times I want to put all possible digits down that can go into a cell.

Being unable to distinguish the two can lead to mistakes and confusion, so it would be nice to have a secondary note mode which, for example, puts all digits centered into the cell instead of around the edge. Here's an example:

Example:

![example one](http://s1.saviola.de/screens/085184.png)

Here, we want to note that *only* 1 and 9 can go into these cells (ignore the dot between the cells). Whereas the normal notation would indicate that 1 and 9, but also other number we haven't looked at yet can go into this cell.

Or this there some way to achieve this distinction that I'm not aware of?

**Comment by e-t-l** [comment]
This seems more like a playstyle issue than a code one. I think most users just note whatever numbers they want. For example, if you have noted that 1 and 9 are possibilities, it's not too hard to run through numbers 2-8 to check if any of them are also possible. If you just  note 1 and 9 without checking the others, and you later return to that cell and can't remember if any other digits are possible, you'll just have to run through 2-8 to check. It's part of the game :)

**Comment by jlnordin** [comment]
Centered notes are included in other Sudoku apps in addition to grid-based
notes, so I think this is a reasonable request. We would need to update the
way we store notes internally as well as updating all of the UI for input
modes to allow for choosing between different notation modes. It's doable,
but is still fairly involved.

**Comment by nikclayton** [comment]
Partial implementation in https://github.com/ogarcia/opensudoku/pull/127

**Comment by ogarcia** [comment]
I'm migrating Open Sudoku development from GitHub to GitLab. To make the migration as clean as possible I'm going to close this issue. If you are still interested (or if it is still relevant), please open it again in [GitLab](https://gitlab.com/opensudoku/opensudoku) from July 26.

Thank you very much for your understanding.
