### ISSUE TITLE
 Unless the opensudoku‘s data is cleared or the opensudoku is reinstalled, some fields of opensudoku will not change the language according to the system settings

### ISSUE THREAD

**Issue by sjl872964789** [ogarcia/opensudoku#92]
**Describe the bug**
Unless the opensudoku‘s data is cleared or the opensudoku is reinstalled, some fields of opensudoku will not change the language according to the system settings (such as: Easy, Medium, Hard)

**Context**
 - Device: [Galaxy A6s]
 - OS version: [Android 7.1.2]
 - App version: [3.4.1]

**How to reproduce**
1. Install opensudoku and open
2. Change to another language in system settings (E.g. Chinese)
3. Back to opensudoku
4. Clear opensudoku from the background and reopen it
5. Unless the data is cleared, some fields of opensudoku will not change the language according to the system settings

**Expected behavior**
opensudoku's language is consistent with the language set by the system setting

**Screenshots**
![ezgif com-video-to-gif (12)](https://user-images.githubusercontent.com/15941953/90950863-25422b00-e488-11ea-9e30-c5db49211d9b.gif)

**Comment by ogarcia** [comment]
This is not an issue. This is the behavior of APP. At first time that you launch the app, the game folders are generated with translates values of "Easy", "Medium" and "Hard", but these names never rename again by the app because they are folders and the user can set the name that he/her wants.

**Comment by sjl872964789** [comment]
But did you notice that at the end of the video, when I cleared the application data and reopened it, these fields were successfully translated into Chinese (简单，中等，困难)

**Comment by ogarcia** [comment]
Yes, because clear application data and launch is the same that launch it at first time :wink:
