### ISSUE TITLE
Some text on the page has not been translated

### ISSUE THREAD

**Issue by sjl872964789** [ogarcia/opensudoku#93]
**Describe the bug**
Some text on the page has not been translated (Chinese)

**Context**
 - Device: [MI CC 9e]/[PIXEL XL]
 - OS version: [MIUI 10.2.10]/[Android 10.0]
 - App version: [3.4.1]

**Expected behavior**
The text is translated correctly

**Screenshots**
screen1:
<img src="https://user-images.githubusercontent.com/15941953/90951565-9553af80-e48e-11ea-89fd-b8602ab91f5d.png" width="270" height="600"/>
screen2:
<img src="https://user-images.githubusercontent.com/15941953/90951569-97b60980-e48e-11ea-8d13-f87a0b47fd83.png" width="270" height="600"/>
screen3:
<img src="https://user-images.githubusercontent.com/15941953/90951585-ba482280-e48e-11ea-819d-c4528f24b9b5.png" width="270" height="600"/>
screen4:
<img src="https://user-images.githubusercontent.com/15941953/90951587-bddba980-e48e-11ea-863e-c68fa1289c67.png" width="270" height="600"/>
screen5:
<img src="https://user-images.githubusercontent.com/15941953/90951590-c0d69a00-e48e-11ea-889f-32af0eee36ec.png" width="270" height="600"/>

**Comment by ogarcia** [comment]
Translations are made by collaborators who do them freely. If you want to collaborate you can send a pull request with missing translations.
Here is [the strings file][1] and [the traslated file][2].

[1]: https://github.com/ogarcia/opensudoku/blob/master/app/src/main/res/values/strings.xml
[2]: https://github.com/ogarcia/opensudoku/blob/master/app/src/main/res/values-zh-rCN/strings.xml
