### ISSUE TITLE
Basque Strings not updated on v3.5.0

### ISSUE THREAD

**Issue by Porrumentzio** [ogarcia/opensudoku#99]
I made the whole translation for Basque but on update to `v3.5.0` on F-Droid, some strings are not translated, concretly those of game level: `Easy`, `Medium`and `Hard`.

Those strings are these:
https://github.com/ogarcia/opensudoku/blob/78dee8123d504736059748591e80fa78505b1540/app/src/main/res/values-eu/strings.xml#L264 https://github.com/ogarcia/opensudoku/blob/78dee8123d504736059748591e80fa78505b1540/app/src/main/res/values-eu/strings.xml#L265 https://github.com/ogarcia/opensudoku/blob/78dee8123d504736059748591e80fa78505b1540/app/src/main/res/values-eu/strings.xml#L266

What happened with those strings? All other strings are translated.

**Comment by ogarcia** [comment]
These strings are well translated. But only works in a new installation (or if you clean app storage) because the `Easy`, `Medium` and `Hard` are folders and you could have renamed them.

**Comment by Porrumentzio** [comment]
Okay, I understand. I'm closing this issue, thanks :)

If I clean app storage I'll loose my done sudokus' times and so on, right?

**Comment by ogarcia** [comment]
> If I clean app storage I'll loose my done sudokus' times and so on, right?

Yes. Is like a new install. I think that is better that you rename folders by hand and test in other device :wink:

**Comment by Porrumentzio** [comment]
I don't find the folders. Anyway, what do you think about letting the app change the folder names according to the translation? In a case of updating or changing the device locales.

Is it very difficult to implement?

**Comment by ogarcia** [comment]
The app behabiour is:
- In first launch creates folders Easy, Medium and Hard with translated names (if has translations).
- If user change language later all application is translated, but no folders because are folders and because the user _CAN RENAME_ it.

If you want change the folders name, long press in one of them and select, _change folder name_.

**Comment by Porrumentzio** [comment]
Understood now, I didn't know about the ability to rename folders
